# -*- coding: utf-8 -*-
"""b22cs001 b22bb016 b22cs093.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BA_ROLkGlep6pHQqv9TJyjyiSyDqfkeo
"""

!python -m spacy download en_core_web_sm

# Import necessary libraries
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import spacy
import re
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report
import os
import tarfile
import urllib.request
from collections import Counter
import random
from sklearn.model_selection import KFold
import sys

# Download and extract IMDB dataset
def download_imdb():
    if not os.path.exists('aclImdb'):
        print("Downloading IMDB dataset...")
        urllib.request.urlretrieve('https://ai.stanford.edu/~amaas/data/sentiment/aclImdb_v1.tar.gz', 'aclImdb_v1.tar.gz')
        print("Extracting IMDB dataset...")
        with tarfile.open('aclImdb_v1.tar.gz', 'r:gz') as tar:
            tar.extractall()
        os.remove('aclImdb_v1.tar.gz')
    else:
        print("IMDB dataset already exists.")

# Download GloVe embeddings
def download_glove(embedding_dim=100):
    if not os.path.exists(f'glove.6B.{embedding_dim}d.txt'):
        print("Downloading GloVe embeddings...")
        os.makedirs('glove', exist_ok=True)
        urllib.request.urlretrieve(
            f'http://nlp.stanford.edu/data/glove.6B.zip',
            'glove.6B.zip'
        )
        print("Extracting GloVe embeddings...")
        import zipfile
        with zipfile.ZipFile('glove.6B.zip', 'r') as zip_ref:
            zip_ref.extractall('.')
        os.remove('glove.6B.zip')
    else:
        print(f"GloVe embeddings (dimension: {embedding_dim}) already exist.")

    return f'glove.6B.{embedding_dim}d.txt'

# Load GloVe embeddings
def load_glove_embeddings(embedding_file, vocab, embedding_dim=100):
    print(f"Loading GloVe embeddings from {embedding_file}...")

    # Initialize embedding matrix with random values
    embedding_matrix = np.random.uniform(-0.25, 0.25, (len(vocab), embedding_dim))

    # Special tokens get zeros
    embedding_matrix[0] = np.zeros(embedding_dim)  # PAD token

    # Load pre-trained GloVe embeddings for words in our vocabulary
    with open(embedding_file, 'r', encoding='utf-8') as f:
        for line in f:
            values = line.split()
            word = values[0]
            if word in vocab:
                embedding_matrix[vocab[word]] = np.array(values[1:], dtype=np.float32)

    print(f"Loaded {embedding_dim}-dimensional GloVe embeddings")
    return embedding_matrix

# Install spaCy English model if not already installed
try:
    nlp = spacy.load('en_core_web_sm')
except OSError:
    import subprocess
    import sys
    subprocess.call([sys.executable, "-m", "spacy", "download", "en_core_web_sm"])
    nlp = spacy.load('en_core_web_sm')

# Load IMDB dataset
def load_imdb_data(split_train_dev=True, sample_size=0.2):
    data = {'train': [], 'dev': [], 'test': []}

    # Load train data (positive)
    pos_files = os.listdir('aclImdb/train/pos')
    # Sample only a portion of the dataset
    sample_size_pos = int(len(pos_files) * sample_size)
    sampled_pos_files = random.sample(pos_files, sample_size_pos)

    for filename in sampled_pos_files:
        if filename.endswith('.txt'):
            with open(os.path.join('aclImdb/train/pos', filename), 'r', encoding='utf-8') as f:
                data['train'].append((f.read(), 1))

    # Load train data (negative)
    neg_files = os.listdir('aclImdb/train/neg')
    # Sample only a portion of the dataset
    sample_size_neg = int(len(neg_files) * sample_size)
    sampled_neg_files = random.sample(neg_files, sample_size_neg)

    for filename in sampled_neg_files:
        if filename.endswith('.txt'):
            with open(os.path.join('aclImdb/train/neg', filename), 'r', encoding='utf-8') as f:
                data['train'].append((f.read(), 0))

    # Shuffle train data
    random.shuffle(data['train'])

    # Split train data into train and dev if required
    if split_train_dev:
        split_idx = int(len(data['train']) * 0.9)
        data['dev'] = data['train'][split_idx:]
        data['train'] = data['train'][:split_idx]

    # Load test data (positive)
    pos_files = os.listdir('aclImdb/test/pos')
    # Sample only a portion of the dataset
    sample_size_pos = int(len(pos_files) * sample_size)
    sampled_pos_files = random.sample(pos_files, sample_size_pos)

    for filename in sampled_pos_files:
        if filename.endswith('.txt'):
            with open(os.path.join('aclImdb/test/pos', filename), 'r', encoding='utf-8') as f:
                data['test'].append((f.read(), 1))

    # Load test data (negative)
    neg_files = os.listdir('aclImdb/test/neg')
    # Sample only a portion of the dataset
    sample_size_neg = int(len(neg_files) * sample_size)
    sampled_neg_files = random.sample(neg_files, sample_size_neg)

    for filename in sampled_neg_files:
        if filename.endswith('.txt'):
            with open(os.path.join('aclImdb/test/neg', filename), 'r', encoding='utf-8') as f:
                data['test'].append((f.read(), 0))

    print(f"Loaded IMDB dataset with sample size {sample_size} ({len(data['train'])} train, {len(data['dev'])} dev, {len(data['test'])} test examples)")

    return data

def load_twitter_data(sample_size=0.2, text_col=None, label_col=None):
    """
    Load Twitter dataset from a CSV file with extensive preprocessing.
    - Supports files with or without headers
    - Cleans and filters out unexpected sentiment labels
    - Removes duplicate rows
    - Performs text preprocessing (URL removal, username normalization, etc.)
    - Handles missing values
    - Provides detailed statistics about the dataset
    """
    try:
        import pandas as pd
        import re
        import string
        from datetime import datetime

        start_time = datetime.now()
        print(f"Started loading data at {start_time.strftime('%H:%M:%S')}")

        # Try loading with no headers first and assign column names
        data = pd.read_csv('twitter_training.csv', header=None, encoding='utf-8',
                          on_bad_lines='warn', low_memory=False)

        # Print initial data information
        print(f"\nOriginal dataset shape: {data.shape}")
        print("Data types in Twitter dataset:")
        print(data.dtypes)
        print("\nFirst few rows of Twitter dataset:")
        print(data.head())

        # Check for missing values in original data
        missing_values = data.isnull().sum()
        print("\nMissing values before preprocessing:")
        print(missing_values)

        # If the file has 4 columns and no headers
        if len(data.columns) == 4 and all(isinstance(col, int) for col in data.columns):
            print("Detected CSV file without headers. Assigning column names based on structure.")
            data.columns = ['id', 'username', 'sentiment', 'text']
            text_col = 'text'
            label_col = 'sentiment'

        # Handle missing values in critical columns
        before_na_drop = len(data)
        data = data.dropna(subset=[text_col, label_col])
        after_na_drop = len(data)
        if before_na_drop != after_na_drop:
            print(f"Removed {before_na_drop - after_na_drop} rows with missing text or sentiment values.")

        # Define sentiment mapping with detailed logging
        sentiment_mapping = {'Positive': 2, 'Neutral': 1, 'Negative': 0}
        print(f"Applied sentiment mapping: {sentiment_mapping}")

        # Check for unique sentiment values in the dataset
        unique_sentiments = data[label_col].unique()
        print(f"Found sentiment values in dataset: {unique_sentiments}")

        # Apply sentiment mapping and filter invalid labels
        data[label_col] = data[label_col].apply(lambda x: sentiment_mapping.get(str(x).strip(), None))

        # Drop rows where sentiment is still None (invalid label like "Irrelevant")
        before_drop = len(data)
        data = data.dropna(subset=[label_col])
        after_drop = len(data)
        print(f"Removed {before_drop - after_drop} rows with invalid sentiment labels.")

        # Text preprocessing functions
        def preprocess_text(text):
            # Convert to lowercase
            text = text.lower()

            # Remove URLs
            text = re.sub(r'https?://\S+|www\.\S+', '[URL]', text)

            # Normalize usernames
            text = re.sub(r'@\w+', '@user', text)

            # Remove extra whitespaces
            text = re.sub(r'\s+', ' ', text).strip()

            # Remove special characters and numbers (optional - commented out as it might remove important context)
            # text = re.sub(r'[^a-zA-Z\s]', '', text)

            # Remove punctuation
            text = text.translate(str.maketrans('', '', string.punctuation))

            return text

        # Apply text preprocessing
        print("Applying text preprocessing...")
        original_texts = data[text_col].copy()
        data[text_col] = data[text_col].astype(str).apply(preprocess_text)

        # Check effect of preprocessing on text length
        data['original_length'] = original_texts.str.len()
        data['processed_length'] = data[text_col].str.len()
        avg_length_reduction = (data['original_length'].mean() - data['processed_length'].mean()) / data['original_length'].mean() * 100
        print(f"Average text length reduction after preprocessing: {avg_length_reduction:.2f}%")

        # Remove duplicate rows with detailed logging
        before_dedup = len(data)
        data = data.drop_duplicates(subset=[text_col, label_col])
        after_dedup = len(data)
        print(f"Removed {before_dedup - after_dedup} duplicate rows ({(before_dedup - after_dedup) / before_dedup * 100:.2f}% of dataset).")

        # Check for very short texts that might not contain useful information
        short_texts = data[data['processed_length'] < 5]
        if len(short_texts) > 0:
            print(f"Warning: Found {len(short_texts)} very short texts (less than 5 chars) that might not be informative.")
            print("Examples of very short texts:")
            print(short_texts[text_col].head(3).tolist())

            # Remove very short texts
            data = data[data['processed_length'] >= 5]
            print(f"Removed {len(short_texts)} very short texts.")

        # Drop the temporary columns used for length calculation
        data = data.drop(columns=['original_length', 'processed_length'])

        print(f"Using '{text_col}' as text column and '{label_col}' as label column")

        # Sample the dataset
        print(f"Sampling dataset with fraction {sample_size}")
        data = data.sample(frac=sample_size, random_state=42)

        # Convert labels to int
        data[label_col] = data[label_col].astype(int)
        print("Successfully converted all labels to integers.")

        # Display detailed label distribution
        label_counts = data[label_col].value_counts().sort_index()
        print(f"Label distribution: {dict(zip(label_counts.index, label_counts.values))}")
        print(f"Label distribution percentages: {dict(zip(label_counts.index, (label_counts.values / len(data) * 100).round(2)))}")

        # Check for class imbalance
        max_class = label_counts.max()
        min_class = label_counts.min()
        imbalance_ratio = max_class / min_class
        print(f"Class imbalance ratio (max/min): {imbalance_ratio:.2f}")

        if imbalance_ratio > 2:
            print("Warning: Dataset has significant class imbalance. Consider using stratified sampling or class weights.")

        # Convert to list of tuples (text, label)
        data_tuples = list(zip(data[text_col], data[label_col]))

        # Output final statistics
        end_time = datetime.now()
        processing_time = (end_time - start_time).total_seconds()
        print(f"\nData processing completed in {processing_time:.2f} seconds")
        print(f"Final dataset size: {len(data_tuples)} examples")

        # Log additional useful statistics for modeling
        print(f"Average text length: {data[text_col].str.len().mean():.2f} characters")
        print(f"Maximum text length: {data[text_col].str.len().max()} characters")

        # Vocabulary statistics
        all_words = " ".join(data[text_col]).split()
        unique_words = set(all_words)
        print(f"Total words: {len(all_words)}")
        print(f"Unique words: {len(unique_words)}")
        print(f"Vocabulary richness (unique/total): {len(unique_words)/len(all_words):.2f}")

        return data_tuples

    except FileNotFoundError:
        print("ERROR: twitter_train.csv file not found in the current directory")
        return None
    except pd.errors.EmptyDataError:
        print("ERROR: The CSV file is empty or contains no valid data")
        return None
    except Exception as e:
        print(f"ERROR: {str(e)}")
        print(f"Error type: {type(e).__name__}")
        import traceback
        traceback.print_exc()
        return None

# Tokenize text using spaCy
def tokenize(text):

    # Ensure text is a string
    if not isinstance(text, str):
        text = str(text)


    # Convert to lowercase
    text = text.lower()

    # Replace URLs with a special token
    text = re.sub(r'https?://\S+|www\.\S+', ' URL ', text)

    # Replace mentions with a special token (for Twitter data)
    text = re.sub(r'@\w+', ' MENTION ', text)

    # Replace hashtags with the word
    text = re.sub(r'#(\w+)', r'\1', text)

    # Replace emojis with words
    text = re.sub(r'[^\w\s,.]', ' ', text)

    # Normalize whitespace
    text = re.sub(r'\s+', ' ', text).strip()

    # Tokenize with spaCy
    doc = nlp(text)

    # Filter out stopwords and punctuation
    tokens = []
    for token in doc:
        if not token.is_stop and not token.is_punct and len(token.text) > 1:
            tokens.append(token.text)

    return tokens

# Build vocabulary from training data
def build_vocabulary(data, min_freq=5):
    word_counts = Counter()

    # Count word frequencies
    for text, _ in data:
        tokens = tokenize(text)
        word_counts.update(tokens)

    # Create vocabulary with words that appear at least min_freq times
    vocab = {'PAD': 0, 'UNK': 1}
    idx = 2

    for word, count in word_counts.items():
        if count >= min_freq:
            vocab[word] = idx
            idx += 1

    return vocab

# Calculate average sentence length
def get_avg_length(data):
    total_tokens = 0
    total_sentences = len(data)

    for text, _ in data:
        tokens = tokenize(text)
        total_tokens += len(tokens)

    return int(total_tokens / total_sentences)

# Convert text to indices
def text_to_indices(text, vocab, max_length):
    tokens = tokenize(text)
    indices = []

    for token in tokens[:max_length]:
        if token in vocab:
            indices.append(vocab[token])
        else:
            indices.append(vocab['UNK'])

    # Pad to max_length
    indices = indices + [vocab['PAD']] * (max_length - len(indices))

    return indices

# SentimentDataset class using GloVe embeddings
# SentimentDataset class using GloVe embeddings
class SentimentDataset(Dataset):
    def __init__(self, data, vocab, embedding_matrix, max_length, num_classes):
        self.data = data
        self.vocab = vocab
        self.embedding_matrix = embedding_matrix
        self.max_length = max_length
        self.num_classes = num_classes

        # Create label mapping if needed
        self.label_mapping = None
        if num_classes == 3:
            # Check if we need to convert string labels to integers
            for _, label in data:
                if isinstance(label, str):
                    self.label_mapping = {'Negative': 0, 'Neutral': 1, 'Positive': 2,
                                         'negative': 0, 'neutral': 1, 'positive': 2,
                                         '0': 0, '1': 1, '2': 2}
                    print(f"Created label mapping for string labels: {self.label_mapping}")
                    break

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        text, label = self.data[idx]
        indices = text_to_indices(text, self.vocab, self.max_length)

        # Convert string labels to integers if mapping exists
        if self.label_mapping is not None and isinstance(label, str):
            if label in self.label_mapping:
                label = self.label_mapping[label]
            else:
                try:
                    label = int(label)
                except (ValueError, TypeError):
                    print(f"Warning: Unknown label '{label}', defaulting to 0")
                    label = 0

        # Handle numeric labels that might be strings
        if isinstance(label, str):
            try:
                label = int(float(label))
            except (ValueError, TypeError):
                print(f"Warning: Could not convert label '{label}' to int, defaulting to 0")
                label = 0

        # Ensure label is the correct numeric type
        if not isinstance(label, (int, float)):
            print(f"Warning: Label '{label}' is not numeric (type: {type(label)}), defaulting to 0")
            label = 0

        # Convert label to tensor
        if self.num_classes == 2:  # Binary
            label_tensor = torch.tensor(float(label), dtype=torch.float32)
        else:  # Multiclass
            label_tensor = torch.tensor(int(label), dtype=torch.long)

        return torch.tensor(indices, dtype=torch.long), label_tensor

# Feed-Forward Neural Network for Sentiment Analysis with Embeddings
class FeedForwardNN(nn.Module):
    def __init__(self, vocab_size, embedding_dim, hidden1_size=256, hidden2_size=128, num_classes=2, embedding_matrix=None, dropout_rate=0.3):
        super(FeedForwardNN, self).__init__()

        self.embedding = nn.Embedding(vocab_size, embedding_dim)

        if embedding_matrix is not None:
            self.embedding.weight = nn.Parameter(torch.FloatTensor(embedding_matrix))
            self.embedding.weight.requires_grad = True

        self.flatten = nn.Flatten()
        self.fc1 = nn.Linear(embedding_dim * 100, hidden1_size)
        self.bn1 = nn.BatchNorm1d(hidden1_size)
        self.relu1 = nn.ReLU()
        self.dropout1 = nn.Dropout(dropout_rate)

        self.fc2 = nn.Linear(hidden1_size, hidden2_size)
        self.bn2 = nn.BatchNorm1d(hidden2_size)
        self.relu2 = nn.ReLU()
        self.dropout2 = nn.Dropout(dropout_rate)

        if num_classes == 2:
            self.output = nn.Linear(hidden2_size, 1)
            self.sigmoid = nn.Sigmoid()
        else:
            self.output = nn.Linear(hidden2_size, num_classes)

    def forward(self, x):
        x = self.embedding(x)
        x = self.flatten(x)

        x = self.fc1(x)
        x = self.bn1(x)
        x = self.relu1(x)
        x = self.dropout1(x)

        x = self.fc2(x)
        x = self.bn2(x)
        x = self.relu2(x)
        x = self.dropout2(x)

        if hasattr(self, 'sigmoid'):
            return self.sigmoid(self.output(x))
        else:
            return self.output(x)

class LSTMNN(nn.Module):
    def __init__(self, vocab_size, embedding_dim, hidden_size=256, num_classes=2, embedding_matrix=None, dropout_rate=0.3):
        super(LSTMNN, self).__init__()

        self.embedding = nn.Embedding(vocab_size, embedding_dim)

        if embedding_matrix is not None:
            self.embedding.weight = nn.Parameter(torch.FloatTensor(embedding_matrix))
            self.embedding.weight.requires_grad = True

        self.lstm = nn.LSTM(embedding_dim, hidden_size, batch_first=True)
        self.dropout = nn.Dropout(dropout_rate)

        # For batch normalization in LSTM, we need to handle the sequence dimension properly
        self.bn = nn.BatchNorm1d(hidden_size)

        if num_classes == 2:
            self.output = nn.Linear(hidden_size, 1)
            self.sigmoid = nn.Sigmoid()
        else:
            self.output = nn.Linear(hidden_size, num_classes)

    def forward(self, x):
        x = self.embedding(x)
        lstm_out, (h_n, _) = self.lstm(x)
        x = h_n.squeeze(0)

        # Apply batch normalization
        x = self.bn(x)

        # Apply dropout before final classification
        x = self.dropout(x)

        if hasattr(self, 'sigmoid'):
            return self.sigmoid(self.output(x))
        else:
            return self.output(x)

def evaluate_model(model, data_loader, criterion, binary=True):
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    model.eval()

    all_preds = []
    all_labels = []
    total_loss = 0

    with torch.no_grad():
        for inputs, labels in data_loader:
            inputs, labels = inputs.to(device), labels.to(device)

            outputs = model(inputs)

            if binary:
                outputs_squeezed = outputs.squeeze()
                loss = criterion(outputs_squeezed, labels)
                predictions = (outputs_squeezed > 0.5).float()
            else:
                loss = criterion(outputs, labels)
                predictions = torch.argmax(outputs, dim=1)

            total_loss += loss.item()
            all_preds.extend(predictions.cpu().numpy())
            all_labels.extend(labels.cpu().numpy())

    accuracy = accuracy_score(all_labels, all_preds)
    avg_loss = total_loss / len(data_loader)
    return accuracy, avg_loss

def train_model(model, train_loader, dev_loader, criterion, optimizer, num_epochs=10, binary=True, patience=3):
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    model.to(device)

    train_losses = []
    dev_losses = []
    dev_accuracies = []
    best_accuracy = 0
    best_model_weights = None

    # Early stopping parameters
    patience_counter = 0
    best_epoch = 0

    for epoch in range(num_epochs):
        model.train()
        total_loss = 0

        for inputs, labels in train_loader:
            inputs, labels = inputs.to(device), labels.to(device)

            optimizer.zero_grad()
            outputs = model(inputs)

            if binary:
                outputs = outputs.squeeze()

            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()

            total_loss += loss.item()

        avg_loss = total_loss / len(train_loader)
        train_losses.append(avg_loss)

        # Evaluate on dev set
        model.eval()
        dev_accuracy, dev_loss = evaluate_model(model, dev_loader, criterion, binary=binary)
        dev_accuracies.append(dev_accuracy)
        dev_losses.append(dev_loss)

        print(f'Epoch {epoch+1}/{num_epochs}, Train Loss: {avg_loss:.4f}, Dev Loss: {dev_loss:.4f}, Dev Accuracy: {dev_accuracy:.4f}')

        # Save best model and check for early stopping
        if dev_accuracy > best_accuracy:
            best_accuracy = dev_accuracy
            best_model_weights = model.state_dict().copy()
            best_epoch = epoch
            patience_counter = 0  # Reset counter
        else:
            patience_counter += 1
            if patience_counter >= patience:
                print(f'Early stopping triggered after epoch {epoch+1}. Best accuracy was at epoch {best_epoch+1}.')
                break

    # Load the best model weights
    model.load_state_dict(best_model_weights)
    print(f"Using best model from epoch {best_epoch+1} with accuracy: {best_accuracy:.4f}")

    return model, train_losses, dev_losses, dev_accuracies

def evaluate_and_report(model, test_loader, criterion, binary=True, label_names=None):
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    model.eval()

    all_preds = []
    all_labels = []
    total_loss = 0

    with torch.no_grad():
        for inputs, labels in test_loader:
            inputs, labels = inputs.to(device), labels.to(device)

            outputs = model(inputs)

            if binary:
                outputs_squeezed = outputs.squeeze()
                loss = criterion(outputs_squeezed, labels)
                predictions = (outputs_squeezed > 0.5).float()
            else:
                loss = criterion(outputs, labels)
                predictions = torch.argmax(outputs, dim=1)

            total_loss += loss.item()
            all_preds.extend(predictions.cpu().numpy())
            all_labels.extend(labels.cpu().numpy())

    # Calculate metrics
    accuracy = accuracy_score(all_labels, all_preds)
    avg_loss = total_loss / len(test_loader)

    if binary:
        precision = precision_score(all_labels, all_preds)
        recall = recall_score(all_labels, all_preds)
        f1 = f1_score(all_labels, all_preds)

        print(f'Test Loss: {avg_loss:.4f}')
        print(f'Test Accuracy: {accuracy:.4f}')
        print(f'Test Precision: {precision:.4f}')
        print(f'Test Recall: {recall:.4f}')
        print(f'Test F1 Score: {f1:.4f}')
    else:
        report = classification_report(all_labels, all_preds, target_names=label_names)
        print(f'Test Loss: {avg_loss:.4f}')
        print(f'Test Accuracy: {accuracy:.4f}')
        print("Classification Report:")
        print(report)

    return accuracy, avg_loss, all_preds, all_labels

# Function to perform cross-validation
def perform_cross_validation(data, model_class, embedding_dim, num_classes=3, k_folds=5):
    # For storing metrics across folds
    fold_accuracies = []
    fold_precisions = []
    fold_recalls = []
    fold_f1s = []

    # Set up K-Fold cross-validation
    kf = KFold(n_splits=k_folds, shuffle=True, random_state=42)

    # For plotting
    train_losses_all_folds = []
    val_losses_all_folds = []
    val_accuracies_all_folds = []

    # For each fold
    for fold, (train_idx, val_idx) in enumerate(kf.split(data)):
        print(f"\nTraining fold {fold+1}/{k_folds}...")

        # Split data
        train_data = [data[i] for i in train_idx]
        val_data = [data[i] for i in val_idx]

        # Create vocabulary from training data for this fold
        vocab = build_vocabulary(train_data)
        max_length = min(100, get_avg_length(train_data))  # Limit to 100 tokens max

        # Load GloVe embeddings
        glove_file = download_glove(embedding_dim)
        embedding_matrix = load_glove_embeddings(glove_file, vocab, embedding_dim)

        # Create datasets
        train_dataset = SentimentDataset(train_data, vocab, embedding_matrix, max_length, num_classes)
        val_dataset = SentimentDataset(val_data, vocab, embedding_matrix, max_length, num_classes)

        # Create dataloaders
        batch_size = 32
        train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
        val_loader = DataLoader(val_dataset, batch_size=batch_size)

        # Initialize model
        if model_class == FeedForwardNN:
            model = model_class(len(vocab), embedding_dim, num_classes=num_classes, embedding_matrix=embedding_matrix, dropout_rate=0.3)
        else:  # LSTM
            model = model_class(len(vocab), embedding_dim, num_classes=num_classes, embedding_matrix=embedding_matrix, dropout_rate=0.3)

        # Set up optimizer and criterion
        criterion = nn.CrossEntropyLoss() if num_classes > 2 else nn.BCELoss()
        optimizer = optim.Adam(model.parameters(), lr=0.001, weight_decay=1e-4)

        # Train model
        model, train_losses, val_losses, val_accuracies = train_model(
            model, train_loader, val_loader, criterion, optimizer,
            num_epochs=10, binary=(num_classes == 2), patience=3
        )

        # Evaluate model
        model.eval()

        # Get predictions
        all_preds = []
        all_labels = []
        device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

        with torch.no_grad():
            for inputs, labels in val_loader:
                inputs, labels = inputs.to(device), labels.to(device)
                outputs = model(inputs)

                if num_classes == 2:
                    predictions = (outputs.squeeze() > 0.5).float()
                else:
                    predictions = torch.argmax(outputs, dim=1)

                all_preds.extend(predictions.cpu().numpy())
                all_labels.extend(labels.cpu().numpy())

        # Calculate metrics
        accuracy = accuracy_score(all_labels, all_preds)

        if num_classes == 2:
            precision = precision_score(all_labels, all_preds)
            recall = recall_score(all_labels, all_preds)
            f1 = f1_score(all_labels, all_preds)
        else:
            precision = precision_score(all_labels, all_preds, average='macro')
            recall = recall_score(all_labels, all_preds, average='macro')
            f1 = f1_score(all_labels, all_preds, average='macro')

        print(f"\nFold {fold+1} Results:")
        print(f"Accuracy: {accuracy:.4f}")
        print(f"Precision: {precision:.4f}")
        print(f"Recall: {recall:.4f}")
        print(f"F1 Score: {f1:.4f}")

        # Store metrics
        fold_accuracies.append(accuracy)
        fold_precisions.append(precision)
        fold_recalls.append(recall)
        fold_f1s.append(f1)

        # Store training curves
        train_losses_all_folds.append(train_losses)
        val_losses_all_folds.append(val_losses)
        val_accuracies_all_folds.append(val_accuracies)

    # Calculate average metrics
    avg_accuracy = np.mean(fold_accuracies)
    avg_precision = np.mean(fold_precisions)
    avg_recall = np.mean(fold_recalls)
    avg_f1 = np.mean(fold_f1s)

    print("\n==== Cross-Validation Results ====")
    print(f"Average Accuracy: {avg_accuracy:.4f}")
    print(f"Average Precision: {avg_precision:.4f}")
    print(f"Average Recall: {avg_recall:.4f}")
    print(f"Average F1 Score: {avg_f1:.4f}")

    # Return metrics and training curves
    metrics = {
        'accuracy': avg_accuracy,
        'precision': avg_precision,
        'recall': avg_recall,
        'f1': avg_f1,
        'fold_accuracies': fold_accuracies,
        'fold_precisions': fold_precisions,
        'fold_recalls': fold_recalls,
        'fold_f1s': fold_f1s,
        'train_losses': train_losses_all_folds,
        'val_losses': val_losses_all_folds,
        'val_accuracies': val_accuracies_all_folds
    }

    return metrics

# Set embedding dimension
embedding_dim = 100

# Download IMDB dataset
download_imdb()

# Process IMDB dataset
imdb_data = load_imdb_data(sample_size=0.2)

# Build vocabulary
imdb_vocab = build_vocabulary(imdb_data['train'])
print(f"IMDB vocabulary size: {len(imdb_vocab)}")

# Calculate average sentence length
imdb_max_length = min(100, get_avg_length(imdb_data['train']))  # Limit to 100 tokens max
print(f"IMDB average sentence length: {imdb_max_length}")

# Download and load GloVe embeddings
glove_file = download_glove(embedding_dim)
imdb_embedding_matrix = load_glove_embeddings(glove_file, imdb_vocab, embedding_dim)

# Create datasets
imdb_train_dataset = SentimentDataset(imdb_data['train'], imdb_vocab, imdb_embedding_matrix, imdb_max_length, num_classes=2)
imdb_dev_dataset = SentimentDataset(imdb_data['dev'], imdb_vocab, imdb_embedding_matrix, imdb_max_length, num_classes=2)
imdb_test_dataset = SentimentDataset(imdb_data['test'], imdb_vocab, imdb_embedding_matrix, imdb_max_length, num_classes=2)

# Create dataloaders
batch_size = 32
imdb_train_loader = DataLoader(imdb_train_dataset, batch_size=batch_size, shuffle=True)
imdb_dev_loader = DataLoader(imdb_dev_dataset, batch_size=batch_size)
imdb_test_loader = DataLoader(imdb_test_dataset, batch_size=batch_size)

# Train Feed-Forward NN
ffnn_binary = FeedForwardNN(len(imdb_vocab), embedding_dim, num_classes=2, embedding_matrix=imdb_embedding_matrix)
binary_criterion = nn.BCELoss()
ffnn_optimizer = optim.Adam(ffnn_binary.parameters(), lr=0.001, weight_decay=1e-4)

print("Training Feed-Forward NN on IMDB dataset...")
ffnn_binary, ffnn_train_losses, ffnn_dev_losses, ffnn_dev_accuracies = train_model(
    ffnn_binary, imdb_train_loader, imdb_dev_loader, binary_criterion, ffnn_optimizer,
    num_epochs=10, binary=True, patience=3
)

# Evaluate Feed-Forward NN
print("\nEvaluating Feed-Forward NN on IMDB test dataset:")
ffnn_accuracy, ffnn_loss, ffnn_preds, ffnn_labels = evaluate_and_report(
    ffnn_binary, imdb_test_loader, binary_criterion, binary=True
)

# Train LSTM
lstm_binary = LSTMNN(len(imdb_vocab), embedding_dim, num_classes=2, embedding_matrix=imdb_embedding_matrix)
lstm_optimizer = optim.Adam(lstm_binary.parameters(), lr=0.001, weight_decay=1e-4)

print("\nTraining LSTM on IMDB dataset...")
lstm_binary, lstm_train_losses, lstm_dev_losses, lstm_dev_accuracies = train_model(
    lstm_binary, imdb_train_loader, imdb_dev_loader, binary_criterion, lstm_optimizer,
    num_epochs=10, binary=True, patience=3
)

# Evaluate LSTM
print("\nEvaluating LSTM on IMDB test dataset:")
lstm_accuracy, lstm_loss, lstm_preds, lstm_labels = evaluate_and_report(
    lstm_binary, imdb_test_loader, binary_criterion, binary=True
)

# Plot training curves for IMDB
plt.figure(figsize=(15, 5))

# Plot training and validation loss
plt.subplot(1, 3, 1)
len_ffnn = len(ffnn_train_losses)
len_lstm = len(lstm_train_losses)
plt.plot(range(1, len_ffnn + 1), ffnn_train_losses, 'b-', label='FFNN Train')
plt.plot(range(1, len_ffnn + 1), ffnn_dev_losses, 'b--', label='FFNN Val')
plt.plot(range(1, len_lstm + 1), lstm_train_losses, 'r-', label='LSTM Train')
plt.plot(range(1, len_lstm + 1), lstm_dev_losses, 'r--', label='LSTM Val')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.title('Loss Curves - IMDB')
plt.legend()

# Plot validation accuracy
plt.subplot(1, 3, 2)
plt.plot(range(1, len_ffnn + 1), ffnn_dev_accuracies, 'b-', label='FFNN')
plt.plot(range(1, len_lstm + 1), lstm_dev_accuracies, 'r-', label='LSTM')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.title('Validation Accuracy - IMDB')
plt.legend()

# Add a comparison bar chart
plt.subplot(1, 3, 3)
models = ['FFNN', 'LSTM']
final_accuracies = [ffnn_dev_accuracies[-1], lstm_dev_accuracies[-1]]
final_losses = [ffnn_dev_losses[-1], lstm_dev_losses[-1]]

x = np.arange(len(models))
width = 0.35

plt.bar(x - width/2, final_accuracies, width, label='Accuracy')
plt.bar(x + width/2, final_losses, width, label='Loss')
plt.axhline(y=0.5, color='gray', linestyle='--', alpha=0.5)  # Baseline for accuracy
plt.xlabel('Models')
plt.title('Final Performance Comparison')
plt.xticks(x, models)
plt.legend()

plt.tight_layout()
plt.savefig('imdb_training_curves.png')
plt.show()

# Process Twitter dataset with 5-fold cross-validation
print("\n===== Twitter Dataset with 5-Fold Cross-Validation =====")
twitter_data = load_twitter_data(sample_size=0.2)

# Only proceed with Twitter dataset if loading was successful
if twitter_data is not None:
    print(f"Twitter dataset size: {len(twitter_data)}")

    # Set number of classes to 3 for Twitter sentiment analysis (multiclass)
    num_classes = 3
    print(f"Using {num_classes} classes for Twitter sentiment analysis")

    # Perform cross-validation for LSTM only
    print("\n===== LSTM Cross-Validation =====")
    lstm_metrics = perform_cross_validation(
        twitter_data, LSTMNN, embedding_dim, num_classes=num_classes
    )

    # Plot training curves for LSTM cross-validation
    plt.figure(figsize=(10, 8))

    # Plot training and validation loss
    plt.subplot(2, 1, 1)
    min_epochs_lstm = min(len(losses) for losses in lstm_metrics['train_losses'])
    for fold, losses in enumerate(lstm_metrics['train_losses']):
        plt.plot(range(1, min_epochs_lstm + 1), losses[:min_epochs_lstm], 'r-', alpha=0.2)
    for fold, losses in enumerate(lstm_metrics['val_losses']):
        plt.plot(range(1, min_epochs_lstm + 1), losses[:min_epochs_lstm], 'r--', alpha=0.2)
    plt.plot(range(1, min_epochs_lstm + 1), np.mean([losses[:min_epochs_lstm] for losses in lstm_metrics['train_losses']], axis=0),
             'r-', linewidth=2, label='LSTM Train Avg')
    plt.plot(range(1, min_epochs_lstm + 1), np.mean([losses[:min_epochs_lstm] for losses in lstm_metrics['val_losses']], axis=0),
             'r--', linewidth=2, label='LSTM Val Avg')
    plt.xlabel('Epoch')
    plt.ylabel('Loss')
    plt.title('LSTM Loss Curves - All Folds')
    plt.legend()

    # Plot validation accuracy
    plt.subplot(2, 1, 2)
    for fold, accs in enumerate(lstm_metrics['val_accuracies']):
        plt.plot(range(1, min_epochs_lstm + 1), accs[:min_epochs_lstm], 'r-', alpha=0.2)
    plt.plot(range(1, min_epochs_lstm + 1), np.mean([accs[:min_epochs_lstm] for accs in lstm_metrics['val_accuracies']], axis=0),
             'r-', linewidth=2, label='LSTM Accuracy')
    plt.xlabel('Epoch')
    plt.ylabel('Accuracy')
    plt.title('LSTM Validation Accuracy - All Folds')
    plt.legend()

    plt.tight_layout()
    plt.savefig('twitter_lstm_training_curves.png')
    plt.show()

    # Show LSTM model performance
    print("\n===== Model Performance (LSTM - Twitter Cross-Validation) =====")
    print(f"{'Metric':<10} {'Score':<10}")
    print("-" * 22)
    print(f"{'Accuracy':<10} {lstm_metrics['accuracy']:<10.4f}")
    print(f"{'Precision':<10} {lstm_metrics['precision']:<10.4f}")
    print(f"{'Recall':<10} {lstm_metrics['recall']:<10.4f}")
    print(f"{'F1 Score':<10} {lstm_metrics['f1']:<10.4f}")

    print("Cross-validation results saved to 'twitter_lstm_training_curves.png'")
else:
    print("Skipping Twitter dataset cross-validation due to loading error.")

# # Save models regardless of Twitter dataset
# print("\nSaving IMDB models and vocabulary...")
# # torch.save(ffnn_binary.state_dict(), 'ffnn_binary_model.pth')
# torch.save(lstm_binary.state_dict(), 'lstm_binary_model.pth')

# # Save vocabularies
# import pickle
# with open('imdb_vocab.pkl', 'wb') as f:
#     pickle.dump(imdb_vocab, f)

# print("Models and vocabularies saved successfully.")